This is makeindex, version 2.16 [MiKTeX 22.3].
Scanning style file ./document.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document.acn....done (45 entries accepted, 0 rejected).
Sorting entries....done (278 comparisons).
Generating output file document.acr....done (37 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
